# Generated by Django 4.1 on 2023-03-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='approved_notice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='deleted_notice',
            field=models.BooleanField(default=False),
        ),
    ]
