# Generated by Django 4.1 on 2023-03-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_reply_approved_reply_approved_notice_reply_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='approved_notice',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='deleted_notice',
        ),
        migrations.AlterField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.author'),
        ),
    ]
